name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_11.4.app
      - name: Build
        run: bazelisk build --subcommands //examples/ios/PureSwift:PureSwiftFramework //examples/ios/PureObjC:PureObjCFramework //examples/ios/Mixed:MixedFramework
